export const currencyMap = {
    "USD": "$", 
    "EUR": "€", 
    "JPY": "¥", 
    "GBP": "£", 
    "AUD": "A$", 
    "CAD": "C$", 
    "CHF": "CHF", 
    "CNY": "¥", 
    "SEK": "kr",
    "NZD": "NZ$",
    "MXN": "MX$", 
    "SGD": "S$", 
    "HKD": "HK$",
    "NOK": "kr", 
    "KRW": "₩",
    "TRY": "₺", 
    "RUB": "₽",
    "INR": "₹", 
    "BRL": "R$", 
    "ZAR": "R", 
  };
